/**
 * Auto-generated by scripts/optimize-images.ts - DO NOT EDIT MANUALLY.
 */

export interface OptimizedImageInfo {
  key: string;
  blurhash: string;
  aspectRatio: number;
  avifSrcSet: string;
  webpSrcSet: string;
  jpegSrcSet: string;
  fallbackSrc: string;
}

export const OPTIMIZED_IMAGES: Record<string, OptimizedImageInfo> = {
  "avatar_user_profile": {
    "key": "avatar_user_profile",
    "blurhash": "LzLNurod.8x]~pofbIt6IVayV@WB",
    "aspectRatio": 1,
    "avifSrcSet": "/images/optimized/avatar_user_profile-320.avif 320w, /images/optimized/avatar_user_profile-640.avif 640w, /images/optimized/avatar_user_profile-1024.avif 1024w",
    "webpSrcSet": "/images/optimized/avatar_user_profile-320.webp 320w, /images/optimized/avatar_user_profile-640.webp 640w, /images/optimized/avatar_user_profile-1024.webp 1024w",
    "jpegSrcSet": "/images/optimized/avatar_user_profile-320.jpg 320w, /images/optimized/avatar_user_profile-640.jpg 640w, /images/optimized/avatar_user_profile-1024.jpg 1024w",
    "fallbackSrc": "/images/optimized/avatar_user_profile-640.jpg"
  },
  "illus_bank_3d": {
    "key": "illus_bank_3d",
    "blurhash": "LlO:|kt8~W%M-qt7fhV@_3oLM|R*",
    "aspectRatio": 1,
    "avifSrcSet": "/images/optimized/illus_bank_3d-320.avif 320w, /images/optimized/illus_bank_3d-640.avif 640w, /images/optimized/illus_bank_3d-1024.avif 1024w",
    "webpSrcSet": "/images/optimized/illus_bank_3d-320.webp 320w, /images/optimized/illus_bank_3d-640.webp 640w, /images/optimized/illus_bank_3d-1024.webp 1024w",
    "jpegSrcSet": "/images/optimized/illus_bank_3d-320.jpg 320w, /images/optimized/illus_bank_3d-640.jpg 640w, /images/optimized/illus_bank_3d-1024.jpg 1024w",
    "fallbackSrc": "/images/optimized/illus_bank_3d-640.jpg"
  },
  "illus_consult_3d": {
    "key": "illus_consult_3d",
    "blurhash": "LTOp_HIn^m%M%gxut7WU~XxaD%R*",
    "aspectRatio": 1,
    "avifSrcSet": "/images/optimized/illus_consult_3d-320.avif 320w, /images/optimized/illus_consult_3d-640.avif 640w, /images/optimized/illus_consult_3d-1024.avif 1024w",
    "webpSrcSet": "/images/optimized/illus_consult_3d-320.webp 320w, /images/optimized/illus_consult_3d-640.webp 640w, /images/optimized/illus_consult_3d-1024.webp 1024w",
    "jpegSrcSet": "/images/optimized/illus_consult_3d-320.jpg 320w, /images/optimized/illus_consult_3d-640.jpg 640w, /images/optimized/illus_consult_3d-1024.jpg 1024w",
    "fallbackSrc": "/images/optimized/illus_consult_3d-640.jpg"
  },
  "illus_gov_3d": {
    "key": "illus_gov_3d",
    "blurhash": "LsOf[c%M_MoK.8ayj?kC_3ofM{WC",
    "aspectRatio": 1,
    "avifSrcSet": "/images/optimized/illus_gov_3d-320.avif 320w, /images/optimized/illus_gov_3d-640.avif 640w, /images/optimized/illus_gov_3d-1024.avif 1024w",
    "webpSrcSet": "/images/optimized/illus_gov_3d-320.webp 320w, /images/optimized/illus_gov_3d-640.webp 640w, /images/optimized/illus_gov_3d-1024.webp 1024w",
    "jpegSrcSet": "/images/optimized/illus_gov_3d-320.jpg 320w, /images/optimized/illus_gov_3d-640.jpg 640w, /images/optimized/illus_gov_3d-1024.jpg 1024w",
    "fallbackSrc": "/images/optimized/illus_gov_3d-640.jpg"
  },
  "illus_health_3d": {
    "key": "illus_health_3d",
    "blurhash": "LcS5*Ht7*J-;-pn*X8bb.mozMcRj",
    "aspectRatio": 1,
    "avifSrcSet": "/images/optimized/illus_health_3d-320.avif 320w, /images/optimized/illus_health_3d-640.avif 640w, /images/optimized/illus_health_3d-1024.avif 1024w",
    "webpSrcSet": "/images/optimized/illus_health_3d-320.webp 320w, /images/optimized/illus_health_3d-640.webp 640w, /images/optimized/illus_health_3d-1024.webp 1024w",
    "jpegSrcSet": "/images/optimized/illus_health_3d-320.jpg 320w, /images/optimized/illus_health_3d-640.jpg 640w, /images/optimized/illus_health_3d-1024.jpg 1024w",
    "fallbackSrc": "/images/optimized/illus_health_3d-640.jpg"
  },
  "illus_hero_banner": {
    "key": "illus_hero_banner",
    "blurhash": "LRK2*N?b.mx]yEWEV@aeyYRkR5Rk",
    "aspectRatio": 1.7917,
    "avifSrcSet": "/images/optimized/illus_hero_banner-320.avif 320w, /images/optimized/illus_hero_banner-640.avif 640w, /images/optimized/illus_hero_banner-1024.avif 1024w",
    "webpSrcSet": "/images/optimized/illus_hero_banner-320.webp 320w, /images/optimized/illus_hero_banner-640.webp 640w, /images/optimized/illus_hero_banner-1024.webp 1024w",
    "jpegSrcSet": "/images/optimized/illus_hero_banner-320.jpg 320w, /images/optimized/illus_hero_banner-640.jpg 640w, /images/optimized/illus_hero_banner-1024.jpg 1024w",
    "fallbackSrc": "/images/optimized/illus_hero_banner-640.jpg"
  },
  "illus_house_3d": {
    "key": "illus_house_3d",
    "blurhash": "LnNdm%tR_3s:xcazoza{~XsnNGW;",
    "aspectRatio": 1,
    "avifSrcSet": "/images/optimized/illus_house_3d-320.avif 320w, /images/optimized/illus_house_3d-640.avif 640w, /images/optimized/illus_house_3d-1024.avif 1024w",
    "webpSrcSet": "/images/optimized/illus_house_3d-320.webp 320w, /images/optimized/illus_house_3d-640.webp 640w, /images/optimized/illus_house_3d-1024.webp 1024w",
    "jpegSrcSet": "/images/optimized/illus_house_3d-320.jpg 320w, /images/optimized/illus_house_3d-640.jpg 640w, /images/optimized/illus_house_3d-1024.jpg 1024w",
    "fallbackSrc": "/images/optimized/illus_house_3d-640.jpg"
  },
  "illus_identity_3d": {
    "key": "illus_identity_3d",
    "blurhash": "LtOgm1WX?Ixt%fxujZNF~EoJI.j]",
    "aspectRatio": 1,
    "avifSrcSet": "/images/optimized/illus_identity_3d-320.avif 320w, /images/optimized/illus_identity_3d-640.avif 640w, /images/optimized/illus_identity_3d-1024.avif 1024w",
    "webpSrcSet": "/images/optimized/illus_identity_3d-320.webp 320w, /images/optimized/illus_identity_3d-640.webp 640w, /images/optimized/illus_identity_3d-1024.webp 1024w",
    "jpegSrcSet": "/images/optimized/illus_identity_3d-320.jpg 320w, /images/optimized/illus_identity_3d-640.jpg 640w, /images/optimized/illus_identity_3d-1024.jpg 1024w",
    "fallbackSrc": "/images/optimized/illus_identity_3d-640.jpg"
  },
  "illus_internet_3d": {
    "key": "illus_internet_3d",
    "blurhash": "LeOEC+kX^i%2x]s:oJWC~As.IpWX",
    "aspectRatio": 1,
    "avifSrcSet": "/images/optimized/illus_internet_3d-320.avif 320w, /images/optimized/illus_internet_3d-640.avif 640w, /images/optimized/illus_internet_3d-1024.avif 1024w",
    "webpSrcSet": "/images/optimized/illus_internet_3d-320.webp 320w, /images/optimized/illus_internet_3d-640.webp 640w, /images/optimized/illus_internet_3d-1024.webp 1024w",
    "jpegSrcSet": "/images/optimized/illus_internet_3d-320.jpg 320w, /images/optimized/illus_internet_3d-640.jpg 640w, /images/optimized/illus_internet_3d-1024.jpg 1024w",
    "fallbackSrc": "/images/optimized/illus_internet_3d-640.jpg"
  },
  "illus_post_3d": {
    "key": "illus_post_3d",
    "blurhash": "LcQb@4xa*0yD.8aeX8of*0kXVXni",
    "aspectRatio": 1,
    "avifSrcSet": "/images/optimized/illus_post_3d-320.avif 320w, /images/optimized/illus_post_3d-640.avif 640w, /images/optimized/illus_post_3d-1024.avif 1024w",
    "webpSrcSet": "/images/optimized/illus_post_3d-320.webp 320w, /images/optimized/illus_post_3d-640.webp 640w, /images/optimized/illus_post_3d-1024.webp 1024w",
    "jpegSrcSet": "/images/optimized/illus_post_3d-320.jpg 320w, /images/optimized/illus_post_3d-640.jpg 640w, /images/optimized/illus_post_3d-1024.jpg 1024w",
    "fallbackSrc": "/images/optimized/illus_post_3d-640.jpg"
  },
  "illus_vehicle_3d": {
    "key": "illus_vehicle_3d",
    "blurhash": "LhPQEYxv?Gxa-;WBM{WE~oRiIWoz",
    "aspectRatio": 1,
    "avifSrcSet": "/images/optimized/illus_vehicle_3d-320.avif 320w, /images/optimized/illus_vehicle_3d-640.avif 640w, /images/optimized/illus_vehicle_3d-1024.avif 1024w",
    "webpSrcSet": "/images/optimized/illus_vehicle_3d-320.webp 320w, /images/optimized/illus_vehicle_3d-640.webp 640w, /images/optimized/illus_vehicle_3d-1024.webp 1024w",
    "jpegSrcSet": "/images/optimized/illus_vehicle_3d-320.jpg 320w, /images/optimized/illus_vehicle_3d-640.jpg 640w, /images/optimized/illus_vehicle_3d-1024.jpg 1024w",
    "fallbackSrc": "/images/optimized/illus_vehicle_3d-640.jpg"
  },
  "illus_welfare_3d": {
    "key": "illus_welfare_3d",
    "blurhash": "L*QSblxt%ht7%NayaebH.Ta#Mxj[",
    "aspectRatio": 1,
    "avifSrcSet": "/images/optimized/illus_welfare_3d-320.avif 320w, /images/optimized/illus_welfare_3d-640.avif 640w, /images/optimized/illus_welfare_3d-1024.avif 1024w",
    "webpSrcSet": "/images/optimized/illus_welfare_3d-320.webp 320w, /images/optimized/illus_welfare_3d-640.webp 640w, /images/optimized/illus_welfare_3d-1024.webp 1024w",
    "jpegSrcSet": "/images/optimized/illus_welfare_3d-320.jpg 320w, /images/optimized/illus_welfare_3d-640.jpg 640w, /images/optimized/illus_welfare_3d-1024.jpg 1024w",
    "fallbackSrc": "/images/optimized/illus_welfare_3d-640.jpg"
  }
};
